# Universe and weights
tickers: [QQQ, SPY]
weights: { QQQ: 0.70, SPY: 0.30 }

# Backtest window
start: 2020-01-01
end: 2025-10-01
outdir: outputs_exit_sweep

# Cash and Sharpe settings
cash_rate_percent: 3.0          # earned on the fraction that is flat
sharpe_rf_percent: 3.0          # Sharpe is excess over bills

# Portfolio level circuit breaker, set to 0.0 to disable
max_drawdown_percent: 0.0

# Hybrid tiered sleeves, three equal parts per symbol, SMA100, SMA200, SMA221
# Entry is 3 days above for all sleeves
# Exit delays are per sleeve, 2 days for SMA100, 1 day for SMA200, 0 days for SMA221
tier_windows: [100, 200, 221]
entry_days_by_window: { "100": 3, "200": 3, "221": 3 }

# Exit-day sets to sweep — 0, 1, 2, 3
exit_day_variants:
  - { "100": 0, "200": 0, "221": 0 }
  - { "100": 1, "200": 1, "221": 1 }
  - { "100": 2, "200": 2, "221": 2 }
  - { "100": 3, "200": 3, "221": 3 }
# Baselines
include_baseline_sma200: true
include_baseline_buyhold: true

# Apply max drawdown overlay to baselines too, for apples to apples, default false
apply_overlay_to_baselines: false
