tickers: [IWF]
weights: { IWF: 1.00 }

start: 2001-05-01
end: 2025-10-01
outdir: outputs_exit_grid

cash_rate_percent: 3.0
sharpe_rf_percent: 3.0

# Tier sets to evaluate in the same run
strategy_tier_sets:
  - [100, 200]
  - [100, 150, 200]
  - [100, 200, 250]

# Entry delays per SMA (applies to sleeves and single-SMA strategies below)
entry_days_by_window: { "100": 3, "150": 3, "200": 3, "250": 3 }

# Auto-generate all 0/1 exit mixes per tier set
auto_binary_exit_grid: true
# (If you ever want custom mixes per set, turn the above off and provide:
# exit_variants_by_set:
#   "[100, 200]":
#     - { "100": 0, "200": 1 }
#     - { "100": 1, "200": 0 }
#   "[100, 200, 221]":
#     - { "100": 1, "200": 1, "221": 0 }
#     - { "100": 0, "200": 1, "221": 1 }
# )

# Baselines
include_baseline_buyhold: true

write_per_year: false

random_sampling:
  enabled: true
  num_samples: 500
  min_years: 5
  max_years: 5