hybrid20_defaults:
  long_window: 200
  short_window: 20
  entry_days: 3
  entry_days_long: 3
  entry_days_short: 3
  exit_days_long: 2
  exit_days_short: 1

hybrid20_grids:
  long_windows: [100, 150, 200, 250]
  short_windows: [10, 15, 20, 30, 50]
  cooldown_days: [0, 1, 2]

  entry_days_long: [1, 2, 3]
  entry_days_short: [1, 2, 3]
  exit_days_long:   [1, 2, 3]
  exit_days_short:  [1, 2, 3]

hybrid20_exclusions: []

tickers: [IVW, IWF, QQQ, SPY]
# weights: { IVW: 1.00 }

start: 2001-05-01
end: 2025-10-01
outdir: outputs_exit_grid

cash_rate_percent: 0
sharpe_rf_percent: 0

default_entry_days: 3
include_baseline_buyhold: true
write_per_year: false

random_sampling:
  enabled: false
  num_samples: 5
  min_years: 5
  max_years: 5
  random_seed: 40
