# config.yml
tickers: [IWF]
weights: { IWF: 1.00 }

start: 2001-05-01
end: 2025-10-01
outdir: outputs_exit_grid

cash_rate_percent: 3.0
sharpe_rf_percent: 3.0

# use slope for entry, D consecutive positive SMA slope days
entry_mode: slope
entry_slope_days_by_window: { "20": 3, "50": 3, "100": 3, "200": 3 }
entry_slope_eps_bps: 0.5

# keep exits unchanged, consecutive closes at or below SMA by window
strategy_tier_sets:
  - [20, 50]
  - [20, 100, 200]
  - [50, 100, 200]

exit_variants_by_set:
  "[20, 50]":
    - { "20": 1, "50": 1 }
    - { "20": 2, "50": 1 }
    - { "20": 1, "50": 2 }
    - { "20": 2, "50": 2 }
  "[20, 100, 200]":
    - { "20": 1, "100": 1, "200": 1 }
    - { "20": 2, "100": 1, "200": 1 }
    - { "20": 1, "100": 2, "200": 1 }
    - { "20": 1, "100": 1, "200": 2 }
    - { "20": 2, "100": 2, "200": 1 }
    - { "20": 2, "100": 1, "200": 2 }
    - { "20": 1, "100": 2, "200": 2 }
    - { "20": 2, "100": 2, "200": 2 }
  "[50, 100, 200]":
    - { "50": 1, "100": 1, "200": 1 }
    - { "50": 2, "100": 1, "200": 1 }
    - { "50": 1, "100": 2, "200": 1 }
    - { "50": 1, "100": 1, "200": 2 }
    - { "50": 2, "100": 2, "200": 1 }
    - { "50": 2, "100": 1, "200": 2 }
    - { "50": 1, "100": 2, "200": 2 }
    - { "50": 2, "100": 2, "200": 2 }

# optional single sleeve runs, names include slope when entry_mode is slope
single_sma_strategies:
  - { name: "sma20_slope3in_price1out",  window: 20,  entry_mode: slope, entry_days: 3, exit_days: 1 }
  - { name: "sma50_slope3in_price2out",  window: 50,  entry_mode: slope, entry_days: 3, exit_days: 2 }
  - { name: "sma100_slope3in_price1out", window: 100, entry_mode: slope, entry_days: 3, exit_days: 1 }
  - { name: "sma200_slope3in_price1out", window: 200, entry_mode: slope, entry_days: 3, exit_days: 1 }

include_baseline_buyhold: true
write_per_year: false

random_sampling:
  enabled: true
  num_samples: 500
  min_years: 5
  max_years: 5
  # random_seed: 42
